elasticsearch.hosts: https://10.21.17.159:9200
elasticsearch.ssl.verificationMode: none
elasticsearch.username: kibanaserver
elasticsearch.password: kibanaserver
elasticsearch.requestHeadersWhitelist: ["securitytenant","Authorization"]
server.port: 5601
server.host: "0.0.0.0"
logging.verbose: false
xpack.apm.ui.enabled: true
# xpack.monitoring.ui.enabled: true
xpack.security.enabled: false
# opendistro_security.multitenancy.enabled: true
# opendistro_security.multitenancy.tenants.preferred: ["Private", "Global"]
# opendistro_security.readonly_mode.roles: ["kibana_read_only"]
opendistro_security.basicauth.login.title: "使用域账号进行登录"
opendistro_security.basicauth.login.subtitle: "登录之后可以查询到内网鲸云的日志/apm数据, nginx日志请前往http://hz-log-kibana.cvtapi.com/"