# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [cvte-7.6]
  pull_request:
    branches: [cvte-7.6]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: cvte-7.6
      - name: Use Node.js 10.22.0
        uses: actions/setup-node@v1
        with:
          node-version: 10.22.0
      - run: npm i yarn -g
      - run: yarn kbn bootstrap
      - run: yarn build --docker
